packages:
  - 'packages/*'
  - docs
  - 'playground/*'

catalog:
  '@microsoft/api-extractor': ^7.58.5
  eslint: ^10.7.0
  react: ^19.2.7
  react-dom: ^19.2.7
  vite-plugin-dts: ^5.0.3
  vue: ^3.5.39

allowBuilds:
  '@parcel/watcher': true
  canvas: true
  esbuild: true

minimumReleaseAge: 0
trustLockfile: true
