packages:
  - 'packages/*'
  - docs
  - 'playground/*'

catalog:
  '@microsoft/api-extractor': ^7.59.0
  eslint: ^10.10.0
  react: ^19.2.8
  react-dom: ^19.2.8
  vite-plugin-dts: ^5.0.3
  vue: ^3.5.41

allowBuilds:
  '@parcel/watcher': true
  canvas: true
  esbuild: true

minimumReleaseAge: 0
trustLockfile: true
