name: CI Pipeline

on:
  workflow_call:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup environment
        uses: './.github/actions/setup-environment'

      - name: install Playwright browsers
        run: npx playwright install --with-deps

      - name: run unit test
        run: pnpm test:unit

      - name: run e2e test
        run: pnpm test:ci-e2e
