name: Prewiew Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  CI:
    uses: './.github/workflows/ci.yml'

  preview:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - uses: actions/checkout@v4
      # - name: setup environment
      #   uses: './.github/actions/setup-environment'
