name: Setup environment

description: Install dependencies

runs:
  using: composite
  steps:
    - name: install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24.11.1
        cache: 'pnpm'

    - name: install dependencies
      shell: bash
      run: pnpm install
