name: Deploy to Production

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'pnpm-lock.yaml'
      - 'package.json'

jobs:
  CI:
    uses: './.github/workflows/ci.yml'

  deploy:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - uses: actions/checkout@v4
      # - name: setup environment
      #   uses: './.github/actions/setup-environment'

      # - name: build production
      #   run: pnpm build:production

      # - name: deploy to production
      #   run: pnpm deploy
