name: CI-Pipeline

on:
  workflow_call:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup environment
        uses: tzuyi0817/coding-standards/.github/actions/setup-environment@main

      - name: run unit test
        run: pnpm test:unit
